modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/mattiebw/SlimeBuckets/issues"
license = "MIT"

[[mods]]
modId = "slimebuckets"
version = "${version}"
displayName = "Slime Buckets"
authors = "Matt Ware"
description = '''
Cute lil slime buckets ^-^
'''
logoFile = "assets/slimebuckets/icon.png"

[[dependencies.slimebuckets]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.slimebuckets]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.slimebuckets]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.slimebuckets]]
modId = "cloth_config"
type = "required"
versionRange = "[15.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "slimebuckets.mixins.json"
